version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - /home/carlos/monitoring_project/roles/monitoring/files/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node_exporter
    ports:
      - "9100:9100"

  sample-app:
    build: ./sample_app
    container_name: sample_app
    ports:
      - "8080:8080"
    command:
      [
        "/bin/main",
        "-listen_address=0.0.0.0:8080",
        "-metric_type=all",
        "-metric_count=5",
        "-datapoint_count=3",
        "-label_count=3",
        "-metric_frequency=1",
        "-is_random"
      ]

  my_flask_app:
    build: ./my_flask_app
    container_name: my_flask_app
    ports:
      - "5000:5000"


volumes:
  prom_data:
  grafana_data:
