scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'sample-app'
    static_configs:
      - targets: ['sample_app:8080']
  - job_name: 'my_flask_app'
    static_configs:
      - targets: ['my_flask_app:5000']
